apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-divy
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0036-tenant/tkrw-pr712-0075-0036-app/devfile-sample-divy@sha256:5a324d2d5ba48a8b87397d052ba79bf7c0bc17f16e2829a381a6419f1d067760
        name: my-nodejs
        resources: {}
status: {}
